
// This file is auto-generated by scripts/download-armor.js
export const ARMOR_MAP: Record<string, { name: string; fileName: string; value: number }> = {
    "822bcab2-40a2-324e-c137-e09195ad7692": {
        "name": "Heavy Armor",
        "fileName": "heavy_armor",
        "value": 50
    },
    "4dec83d5-4902-9ab3-bed6-a7a390761157": {
        "name": "Light Armor",
        "fileName": "light_armor",
        "value": 25
    },
    "b1b9086d-41bd-a516-5d29-e3b34a6f1644": {
        "name": "Regen Shield",
        "fileName": "regen_shield",
        "value": 50
    }
};
