const fs = require('fs');
const path = require('path');
const https = require('https');

const ARMOR_DIR = path.join(__dirname, '..', 'public', 'armor');

// Create armor directory if it doesn't exist
if (!fs.existsSync(ARMOR_DIR)) {
    fs.mkdirSync(ARMOR_DIR, { recursive: true });
}

function downloadImage(url, filename) {
    return new Promise((resolve, reject) => {
        const filePath = path.join(ARMOR_DIR, filename);
        const file = fs.createWriteStream(filePath);

        https.get(url, (response) => {
            response.pipe(file);
            file.on('finish', () => {
                file.close();
                console.log(`Downloaded: ${filename}`);
                resolve();
            });
        }).on('error', (err) => {
            fs.unlink(filePath, () => { });
            reject(err);
        });
    });
}

async function main() {
    console.log('Fetching armor data from Valorant API...');

    const response = await fetch('https://valorant-api.com/v1/gear');
    const data = await response.json();

    if (data.status !== 200) {
        console.error('Failed to fetch armor data');
        return;
    }

    const armorMap = {};

    for (const gear of data.data) {
        const uuid = gear.uuid.toLowerCase();
        const name = gear.displayName;
        const fileName = name.toLowerCase().replace(/\s+/g, '_');

        // Get the value from the description
        let value = 0;
        if (name === 'Heavy Armor') value = 50;
        else if (name === 'Light Armor') value = 25;
        else if (name === 'Regen Shield') value = 50; // Regen Shield has 50 pool

        armorMap[uuid] = {
            name: name,
            fileName: fileName,
            value: value
        };

        // Download the display icon
        if (gear.displayIcon) {
            try {
                await downloadImage(gear.displayIcon, `${fileName}.png`);
            } catch (err) {
                console.error(`Failed to download ${name}:`, err.message);
            }
        }
    }

    // Generate armor-constants.ts
    const constantsPath = path.join(__dirname, '..', 'src', 'lib', 'armor-constants.ts');
    const constantsContent = `
// This file is auto-generated by scripts/download-armor.js
export const ARMOR_MAP: Record<string, { name: string; fileName: string; value: number }> = ${JSON.stringify(armorMap, null, 4)};
`;

    fs.writeFileSync(constantsPath, constantsContent);
    console.log(`\nGenerated armor constants at: ${constantsPath}`);
    console.log(`\nDownloaded ${Object.keys(armorMap).length} armor icons to: ${ARMOR_DIR}`);
}

main().catch(console.error);
